//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.BidProduct = new HashSet<BidProduct>();
        }
    
        public int id { get; set; }
        public string bid_number { get; set; }
        public int counterparty_id { get; set; }
        public System.DateTime create_date { get; set; }
        public int status_id { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidProduct> BidProduct { get; set; }
    }
}
