//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidProduct
    {
        public int id { get; set; }
        public int bid_id { get; set; }
        public int product_id { get; set; }
        public int product_count { get; set; }
        public int product_price { get; set; }
    
        public virtual Bid Bid { get; set; }
        public virtual Product Product { get; set; }
    }
}
