//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterpartyAttrs
    {
        public int id { get; set; }
        public int counterparty_id { get; set; }
        public int attr_id { get; set; }
        public string attr_value { get; set; }
        public string deleted { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Dictionary Dictionary { get; set; }
    }
}
