//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KRISEntities : DbContext
    {
        public KRISEntities()
            : base("name=KRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bid> Bid { get; set; }
        public virtual DbSet<BidProduct> BidProduct { get; set; }
        public virtual DbSet<Counterparty> Counterparty { get; set; }
        public virtual DbSet<CounterpatryAttrs> CounterpatryAttrs { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<Entity> Entity { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductAttrs> ProductAttrs { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
