//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int id { get; set; }
        public string username { get; set; }
        public string action { get; set; }
        public System.DateTime acttime { get; set; }
    }
}
