//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRIS.database.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string deleted { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}
